### ISSUE TITLE
CNV Plot is not correct

### ISSUE THREAD

**Issue by yuankunzhu** [d3b-center/OMPARE#3] opened 2020-03-17 16:11 UTC
For patient 09, control-freec called the 2p gain but the report missed
- control-freec plot: ![Screen Shot 2020-03-17 at 12 10 09 PM](https://user-images.githubusercontent.com/4965924/76876417-4901a500-6848-11ea-96f5-c3328e98dbc3.png)
- report plot: 
![Screen Shot 2020-03-17 at 12 11 00 PM](https://user-images.githubusercontent.com/4965924/76876503-6767a080-6848-11ea-9c1b-81ce0737bfa8.png)

Patient-09 cavatica folder: https://cavatica.sbgenomics.com/u/cavatica/sd-8y99qzjj/files/#q?path=PNOC008-9

Seems the `*.CNVs.p.value.txt` file has been loaded via code below
https://github.com/d3b-center/OMPARE/blob/cb6704a8a891662f276da2da736c4d2907240b21/code/readData.R#L80-L83

then `copynumber::plotGenome` was used for the plot
https://github.com/d3b-center/OMPARE/blob/cb6704a8a891662f276da2da736c4d2907240b21/code/plotCNV.R#L10-L11

based on the log2() ration using the actual copy_number
https://github.com/d3b-center/OMPARE/blob/cb6704a8a891662f276da2da736c4d2907240b21/code/plotCNV.R#L7

need to use a real SEG file for this function.

**Comment by komalsrathi** [comment] 2020-03-22 17:43
@yuankunzhu do we want to recreate those exact plots (one plot per chromosome)? If yes, would it make sense to just upload those as a png/pdf to the html report? Or you want a single genome wide plot? I am going to have a call with Adam tomorrow at 10 am regarding this.

**Comment by aadamk** [comment] 2020-03-23 15:01
From the call with @komalsrathi, key action items are: 

1) Eliminate log2 transformation from plotCNV.R code (line 7) and instead report normalized CNV call directly from Control-FreeC.

2) Verify that the CN value reported in ```*.CNVs.p.value.txt``` output files is the same as what is utilized by the default Control-FreeC plotter. 

3) Leverage PBTA data to contextualize PNOC-0008 samples by a CNV + gene expression oncoprint - 
```inputs: gene expression profile of genes of interest (HUGO gene identifier) from PNOC-0008 sample + PBTA cohort.```
```output: oncoprint highlighting PNOC-0008 sample ID to show where it falls amongst PBTA samples - cluster based on gene expression data, make a top annotation for corresponding copy number states for those genes. ```

**Comment by komalsrathi** [comment] 2020-03-25 14:37
@aadamk it looks like they use a `*_ratio.txt` file and `ploidy` (which can be obtained from a `_info.txt` file) as input to generate the plots: 

See below from here:  http://boevalab.inf.ethz.ch/FREEC/tutorial.html#OUTPUT 

```
You can visualize normalized copy number profile with predicted CNAs as well as BAF profile by running makeGraph.R:
cat makeGraph.R | R --slave --args < ploidy > < *_ratio.txt > [< *_BAF.txt >]
```

The `makeGraph.R` script is here: https://github.com/BoevaLab/FREEC/blob/master/scripts/makeGraph.R

@migbro @zhangb1 do we have `*_ratio.txt` file and `_info.txt ` outputs for Control-FREEC?

**Comment by zhangb1** [comment] 2020-03-25 15:03
@komalsrathi Yes, we have ` *_ratio.txt file `and` _info.txt  ` as output in our somatic CNV pipeline.

**Comment by komalsrathi** [comment] 2020-03-25 15:06
@zhangb1 where are those files?  I couldn't find under https://cavatica.sbgenomics.com/u/cavatica/sd-8y99qzjj/files/#q?path=PNOC008-9

**Comment by zhangb1** [comment] 2020-03-25 15:17
@komalsrathi we didn't deliver those files as standard delivery, they are in the analysis
project . not in the delivery project.

**Comment by komalsrathi** [comment] 2020-03-25 15:21
Can you point me to that folder?

**Comment by zhangb1** [comment] 2020-03-25 15:33
@komalsrathi  for PNOC008-9 
https://cavatica.sbgenomics.com/u/kfdrc-harmonization/sd-8y99qzjj/files/5e66febbe4b05495adeba885/

https://cavatica.sbgenomics.com/u/kfdrc-harmonization/sd-8y99qzjj/files/5e66febbe4b05495adeba891/

**Comment by aadamk** [comment] 2020-03-26 12:27
@komalsrathi 
Yes, it seems as though they plot the ratio or relative copy number by default, whereas the report code was pulling the absolute copy number column from the ```*p.value.txt``` files and log-transforming. Likely the reason for the difference between plots.

**Comment by komalsrathi** [comment] 2020-03-26 19:12
@aadamk @yuankunzhu I am now using the ratio.txt file. How does this look:

![image](https://user-images.githubusercontent.com/7000615/77686979-1f492c00-6f74-11ea-88b2-076e3e238d7e.png)

**Comment by aadamk** [comment] 2020-03-26 20:37
@komalsrathi  
Looks more consistent though it seems as though a source of variation still exists - for instance, the chr1 het loss (normalized copy number of 1) from the control-freec plot doesn't seem to be reproduced in the above plot. 
Which column are you pulling from the ratio file? Also, are you directly plotting the value or transforming prior to plotting? If you have a snippet or link to the file, that would also be great.

**Comment by komalsrathi** [comment] 2020-03-27 12:39
@aadamk hmm, you are right. Here is my code:

```
ratio <-read.table('ba7e07ac-7878-47e2-9641-c2557bd02356.controlfreec.ratio.txt', header=TRUE)
tmp <- ratio[,c('Chromosome', 'Start', 'CopyNumber')]
tmp.seg <- copynumber::pcf(data = tmp, verbose = FALSE)
copynumber::plotGenome(tmp, tmp.seg)
```

Using makeGraph.R script, I was able to recreate the control-freec chromosome-level plots but wasn't successful at creating a single genome level view. I will try again today.

**Comment by aadamk** [comment] 2020-03-27 15:24
Thanks @komalsrathi 
I noticed from the ```pcf``` function from the ```copynumber``` package contains an option for normalizing the cn estimates by the standard error. It is by default set to ```TRUE``` - might be good to explore if setting to ```FALSE``` would lead to better concordance with the default freeC plot. It may not be a necessary normalization step in our case given that control-freeC already has its own normalization procedure.

**Comment by aadamk** [comment] 2020-03-27 17:35
Also @komalsrathi, given the 4/10 deadline for the PNOC-0008 clinical reports, I'm attaching R code for generating a clustered expression heatmap. Some of the code was specific to the structure of a dataset I was working with in the past and thus some lines may not be relevant to the input files that you use. 

[exp_heatmap_annotated.zip](https://github.com/d3b-center/OMPARE/files/4395077/exp_heatmap_annotated.zip)


Otherwise, this code provides a framework for selecting a subset of genes based on an input character vector (```genelist``` variable), re-scaling expression data to z-scores, generating a top annotation for the heatmap, and generating a clustered output. 

Can you add on to the expression plot the following properties? 
1) A gene-specific CNV heatmap according to the ```genelist``` of interest to go along with the expression plot (e.g. like in panel c of this image?), and cluster by expression? 

![](https://www.researchgate.net/profile/Giulio_Ferrero/publication/331373590/figure/fig3/AS:730821480681473@1551252827207/Characterization-of-chr12p13-amplified-PDAs-and-cell-lines-A-Heat-map-showing-the.png)

2) Leverage OpenPBTA in this plot to contextualize the samples like we discussed? 

3) For a given clinical report, can you highlight the PNOC sample ID of interest within the heatmap (e.g. for sample 10 for instance, highlight or make the label for PNOC-0008-10 a different color for its report to highlight where it falls amongst other samples)?

4) Include a top annotation of clinical variables (specifically race, gender, disease subtype)?  I can point you to a clinical file if you need.

**Comment by komalsrathi** [comment] 2020-03-27 19:43
> Thanks @komalsrathi
> I noticed from the `pcf` function from the `copynumber` package contains an option for normalizing the cn estimates by the standard error. It is by default set to `TRUE` - might be good to explore if setting to `FALSE` would lead to better concordance with the default freeC plot. It may not be a necessary normalization step in our case given that control-freeC already has its own normalization procedure.

This is the plot with `normalize = FALSE`

![image](https://user-images.githubusercontent.com/7000615/77794076-9f899300-7041-11ea-9aec-8251a8988bea.png)

**Comment by aadamk** [comment] 2020-04-01 15:51
CNV plot issue looks to be resolved with the above corrections (using ```ratio.txt``` file and setting ```normalize``` to false within the ```copynumber::pcf``` function), which we should now use retrospectively as well as for upcoming clinical reports for PNOC-0008. 

Closing for now.

**Closed by aadamk** 2020-04-01 15:51 UTC
